Generate and source config file.

diff --git a/bin/deploy_to_test b/bin/deploy_to_test
--- a/bin/deploy_to_test
+++ b/bin/deploy_to_test
@@ -9,12 +9,18 @@
 # around--creating directory structure: releases, shared/files,
 # modifying/uploading settings.php
 
+# Load config
+if [ ! -e bin/.config ]; then
+  echo "Error: could not find configuration file. Please run make-install-profile."
+  exit 2
+fi
+source bin/.config
+
 # Change $SUBDOMAIN accordingly, e.g. <mountain name>
 # Rather than set $USER, use the user we were run as.
 SUBDOMAIN=
 HOST=gargravarr
 INSTALLROOT=/var/www/$SUBDOMAIN
-INSTALLPROFILE=os_project
 PRODUCTIONURL=http://
 
 # Default behavior: Don't touch the test host's database.
@@ -78,7 +84,7 @@ ln -s $INSTALLROOT/releases/$TIMESTAMP $INSTALLROOT/current
 
 if [ -n "$SITEINSTALL" ]; then
   # Re-install the site.
-  drush @$SUBDOMAIN site-install -y --uri=default $INSTALLPROFILE
+  drush @$SUBDOMAIN site-install -y --uri=default $PROFILE
   if [ $? -gt 0 ]; then
     exit 1
   fi
diff --git a/bin/rebuild b/bin/rebuild
--- a/bin/rebuild
+++ b/bin/rebuild
@@ -1,19 +1,19 @@
 #!/bin/bash
 #
-# @@ Replace os_project with the actual project name, then remove this line @@
-# @@ Replace os_theme with the intended theme name, then remove this line @@
-#
 # Rebuild os_project in the drupal directory.
 #
 # To use this command you must have `drush make`, `cvs` and `git` installed.
 #
 
-PROFILE="os_project"
-# Use Compass to compile CSS from source scss files.
-THEME="os_theme"
+# Load config
+if [ ! -e bin/.config ]; then
+  echo "Error: could not find configuration file. Please run make-install-profile."
+  exit 2
+fi
+source bin/.config
 
 # Generate a complete Drupal build.
-echo "Building PROJECT..."
+echo "Building $PROJECTNAME..."
 
 # Remove contrib directories
 DIRECTORIES="drupal
